name: login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
    
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  logger: ^1.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  http_parser: ^4.1.2
  camera: ^0.11.1
  avatar_glow: ^3.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/f0.jpg
    - assets/f1.jpg
    - assets/f2.jpg
    - assets/b0.jpg
    - assets/b1.jpg
    - assets/b2.jpg
    - assets/BeReal_logo.png
    - assets/lmu_logo.png
    - assets/maxmuster.jpg
    - assets/smiley.png
    - assets/f0_emoji.jpg
    - assets/f1_emoji.jpg
    - assets/f2_emoji.jpg
    - assets/ReactSmiley.png
    - assets/Comment.png
    - assets/sad.png
    - assets/angry.png
    - assets/neutral.png
    - assets/surprised.png
    - assets/happy.png
    - assets/default_user.jpeg
    - .env
    
