name: login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4
    
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/br1.jpg
    - assets/br2.jpg
    - assets/br3.jpg
    - assets/br4.jpg
    - assets/f0.jpg
    - assets/f1.jpg
    - assets/f2.jpg
    - assets/b0.jpg
    - assets/b1.jpg
    - assets/b2.jpg
    - assets/BeReal_logo.png
    - assets/lmu_logo.png
    - assets/maxmuster.jpg
    - .env
